name: dbt_test_mmm
version: "1.0.0"
config-version: 2

profile: dbt_test_mmm

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  dbt_test_mmm:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
